export const NEW_CARD_SHOW = 'REPEAT_WORDS/NEW_CARD_SHOW';
export const CORRECT_CARD = 'REPEAT_WORDS/CORRECT_CARD';
export const SAVE_WORD_TO_STATE = 'REPEAT_WORDS/SAVE_WORD_TO_STATE';
export const NEW_CARD_VALUE_SHOWS = 'REPEAT_WORDS/NEW_CARD_VALUE_SHOWS';
export const NEXT_NEW_CARD = 'REPEAT_WORDS/NEXT_NEW_CARD';
export const ADD_TO_DISPLAYED_WORDS_LIST = 'REPEAT_WORDS/ADD_TO_DISPLAYED_WORDS_LIST';
export const SHOW_RESULT = 'REPEAT_WORDS/SHOW_RESULT';
export const RESET_STORE_REPEAT_WORDS = 'REPEAT_WORDS/RESET_STORE_REPEAT_WORDS';
