export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const HIDE_LOADER_OLD_GAME = 'HIDE_LOADER_OLD_GAME';
export const SHOW_LOADER_OLD_GAME = 'SHOW_LOADER_OLD_GAME';
