export const SAVE_FULL_STATISTIC = 'STATISTIC/SAVE_FULL_STATISTIC';
export const GET_STATISTIC_FROM_API = 'STATISTIC/GET_STATISTIC_FROM_API';
export const SAVE_FULL_STATISTIC_TO_STORE = 'STATISTIC/SAVE_FULL_STATISTIC_TO_STORE';
export const SET_LEARN_WORDS_STATISTIC = 'STATISTIC/SET_LEARN_WORDS_STATISTIC';
export const SAVE_FULL_STATISTIC_TO_SERVER = 'STATISTIC/SAVE_FULL_STATISTIC_TO_SERVER';
export const SAVE_REPEAT_STATISTIC = 'STATISTIC/SAVE_REPEAT_STATISTIC';
