export const PLAYFIELD_WIDTH = 720;
export const PLAYFIELD_HEIGHT = 404;
export const PUZZLE_PADDING = 15;
export const PUZZLE_HEIGHT = PLAYFIELD_HEIGHT / 10;
export const ROWS_IN_PAGE = 10;

export const TARGET_ID = 'TARGET_ID';
export const SOURCE_ID = 'SOURCE_ID';

export const PLAYFIELD_WIDTH_LAPTOP = 410;
export const PLAYFIELD_HEIGHT_LAPTOP = 230;
export const PUZZLE_HEIGHT_LAPTOP = PLAYFIELD_HEIGHT_LAPTOP / 10;
export const PUZZLE_PADDING_LAPTOP = 10;
