export const GAME_CHANGE_LEVEL = 'GAME_CHANGE_LEVEL';
export const GAME_CHANGE_PAGE = 'GAME_CHANGE_PAGE';
export const CHANGE_WORDS_COLLECTION = 'CHANGE_WORDS_COLLECTION';
export const CHANGE_I_DONT_KNOW_WORDS = 'CHANGE_I_DONT_KNOW_WORDS';
export const GAME_CHANGE_SCORE = 'GAME_CHANGE_SCORE';
export const GHANGE_GAME_MODE = 'GHANGE_GAME_MODE';
