export const SPEAKIT_CHANGE_LEVEL = 'SPEAKIT_CHANGE_LEVEL';
export const SPEAKIT_CHANGE_PAGE = 'SPEAKIT_CHANGE_PAGE';
export const CHANGE_WORDS_COLLECTION = 'CHANGE_WORDS_COLLECTION';
export const CHANGE_I_DONT_KNOW_WORDS = 'CHANGE_I_DONT_KNOW_WORDS';
