export const AUTH_TO_SERVER = 'AUTH/LOGIN/AUTH_TO_SERVER';
export const SAVE_SESSION_DATA = 'AUTH/LOGIN/SAVE_SESSION_DATA';
export const RESET_SESSION_DATA = 'AUTH/LOGIN/RESET_SESSION_DATA';
export const CHECK_SESSION_STATUS = 'AUTH/LOGIN/CHECK_SESSION_STATUS';
export const IS_ALREADY_CHECK_SESSION_STATUS = 'AUTH/LOGIN/IS_ALREADY_CHECK_SESSION_STATUS';
